--
-- Please see the license.html file included with this distribution for
-- attribution and copyright information.
--

DEFAULT_DICESKIN_GROUP = "DEFAULT";

local _tDiceSkinGroups = {
	"DEFAULT",
	"SWKPROMODICE",
	"SWKELEMENTALBASICSDICE",
	"SWKMETALDICE",
	"SWKAURADICE",
	"SWKMAGICALDICE",
	"SWKRINGOFELEMENTSDICE",
	"SWKMAGICALTRAILDICE",
	"SWKFORCEFIELDDICE",
	"SWKWIZARDWROUGHTDICE",
	"SWKARTIFICERDICE",
	"SWKANNULUSOFFOCUSDICE",
	"SWKANNULUSOFFOCUSDICEFX",
	"SWKKNOTSOFFATEDICE",
	"SWKKNOTSOFFATEDICEFX",
	"SWKBLOODDICE",
	"SWKSTARSANDCLOVERS",
	"SWKHEARTSANDSKULLS",
	"SWKDRAGONSDICE1",
	"SWKMONSTERSDICE1",
	"SWKMONSTERSDICE2",
	"SWKFANTASYDICE1",
	"SWKFANTASYDICE2",
};

local _tDiceSkinGroupStoreID = {
	["SWKMETALDICE"] = "SWKMETALDICE",
	["SWKAURADICE"] = "SWKAURADICE",
	["SWKMAGICALDICE"] = "SWKMAGICALDICE",
	["SWKRINGOFELEMENTSDICE"] = "SWKRINGOFELEMENTSDICE",
	["SWKMAGICALTRAILDICE"] = "SWKMAGICALTRAILDICE",
	["SWKFORCEFIELDDICE"] = "SWKFORCEFIELDDICE",
	["SWKWIZARDWROUGHTDICE"] = "SWKWIZARDWROUGHTDICE",
	["SWKARTIFICERDICE"] = "SWKARTIFICERDICE",
	["SWKANNULUSOFFOCUSDICE"] = "SWKANNULUSOFFOCUSDICE",
	["SWKANNULUSOFFOCUSDICEFX"] = "SWKANNULUSOFFOCUSDICE",
	["SWKKNOTSOFFATEDICE"] = "SWKKNOTSOFFATEDICE",
	["SWKKNOTSOFFATEDICEFX"] = "SWKKNOTSOFFATEDICE",
	["SWKBLOODDICE"] = "SWKBLOODDICE",
	["SWKSTARSANDCLOVERS"] = "SWKSTARSANDCLOVERS",
	["SWKHEARTSANDSKULLS"] = "SWKHEARTSANDSKULLS",
	["SWKMONSTERSDICE1"] = "SWKMONSTERSDICE1",
	["SWKDRAGONSDICE1"] = "SWKDRAGONSDICE1",
	["SWKMONSTERSDICE2"] = "SWKMONSTERSDICE2",
	["SWKFANTASYDICE1"] = "SWKFANTASYDICE1",
	["SWKFANTASYDICE2"] = "SWKFANTASYDICE2",
};

local _tDiceSkinIDStoreID = {
	[346] = "WOTC50DD",
	[347] = "WOTC50DD",
	[348] = "WOTC50EFOTA",
	[349] = "WOTC50EFOTA",
	[350] = "BWGFGCOSSLHB",
	[351] = "BWGFGCOSSLHB",
};

local _tDiceSkinToGroupMap = {
	[0] = "DEFAULT",
	[2] = "SWKMETALDICE", [3] = "SWKMETALDICE", [4] = "SWKMETALDICE", [5] = "SWKMETALDICE",
	[6] = "SWKMETALDICE", [7] = "SWKMETALDICE", [8] = "SWKMETALDICE", [9] = "SWKMETALDICE",
	[10] = "SWKAURADICE", [11] = "SWKAURADICE", [12] = "SWKAURADICE", [13] = "SWKAURADICE", [14] = "SWKAURADICE",
	[15] = "SWKAURADICE", [16] = "SWKAURADICE", [17] = "SWKAURADICE", [18] = "SWKAURADICE", [19] = "SWKAURADICE",
	[20] = "SWKAURADICE", [21] = "SWKAURADICE", [22] = "SWKAURADICE", [23] = "SWKAURADICE", [24] = "SWKAURADICE",
	[25] = "SWKAURADICE", [26] = "SWKAURADICE", [27] = "SWKAURADICE", [28] = "SWKAURADICE", [29] = "SWKAURADICE",
	[30] = "SWKMAGICALDICE", [31] = "SWKMAGICALDICE", [32] = "SWKMAGICALDICE", [33] = "SWKMAGICALDICE", [34] = "SWKMAGICALDICE",
	[35] = "SWKMAGICALDICE", [36] = "SWKMAGICALDICE", [37] = "SWKMAGICALDICE", [38] = "SWKMAGICALDICE", [39] = "SWKMAGICALDICE",
	[40] = "SWKRINGOFELEMENTSDICE", [41] = "SWKRINGOFELEMENTSDICE", [42] = "SWKRINGOFELEMENTSDICE", [43] = "SWKRINGOFELEMENTSDICE", [44] = "SWKRINGOFELEMENTSDICE",
	[45] = "SWKRINGOFELEMENTSDICE", [46] = "SWKRINGOFELEMENTSDICE", [47] = "SWKRINGOFELEMENTSDICE", [48] = "SWKRINGOFELEMENTSDICE", [49] = "SWKRINGOFELEMENTSDICE",
	[50] = "SWKRINGOFELEMENTSDICE", [51] = "SWKRINGOFELEMENTSDICE", [52] = "SWKRINGOFELEMENTSDICE", [53] = "SWKRINGOFELEMENTSDICE", [54] = "SWKRINGOFELEMENTSDICE",
	[55] = "SWKRINGOFELEMENTSDICE", [56] = "SWKRINGOFELEMENTSDICE", [57] = "SWKRINGOFELEMENTSDICE", [58] = "SWKRINGOFELEMENTSDICE", [59] = "SWKRINGOFELEMENTSDICE",
	[60] = "SWKMAGICALTRAILDICE", [61] = "SWKMAGICALTRAILDICE", [62] = "SWKMAGICALTRAILDICE", [63] = "SWKMAGICALTRAILDICE", [64] = "SWKMAGICALTRAILDICE",
	[65] = "SWKMAGICALTRAILDICE", [66] = "SWKMAGICALTRAILDICE", [67] = "SWKMAGICALTRAILDICE", [68] = "SWKMAGICALTRAILDICE", [69] = "SWKMAGICALTRAILDICE",
	[70] = "SWKMAGICALTRAILDICE", [71] = "SWKMAGICALTRAILDICE", [72] = "SWKMAGICALTRAILDICE", [73] = "SWKMAGICALTRAILDICE", [74] = "SWKMAGICALTRAILDICE",
	[75] = "SWKMAGICALTRAILDICE", [76] = "SWKMAGICALTRAILDICE", [77] = "SWKMAGICALTRAILDICE", [78] = "SWKMAGICALTRAILDICE", [79] = "SWKMAGICALTRAILDICE",
	[80] = "SWKFORCEFIELDDICE", [81] = "SWKFORCEFIELDDICE", [82] = "SWKFORCEFIELDDICE", [83] = "SWKFORCEFIELDDICE", [84] = "SWKFORCEFIELDDICE",
	[85] = "SWKFORCEFIELDDICE", [86] = "SWKFORCEFIELDDICE", [87] = "SWKFORCEFIELDDICE", [88] = "SWKFORCEFIELDDICE", [89] = "SWKFORCEFIELDDICE",
	[90] = "DEFAULT", [91] = "SWKFORCEFIELDDICE", [92] = "SWKMETALDICE", [93] = "SWKMETALDICE",
	[94] = "SWKELEMENTALBASICSDICE", [95] = "SWKELEMENTALBASICSDICE", [96] = "SWKELEMENTALBASICSDICE", [97] = "SWKELEMENTALBASICSDICE", [98] = "SWKELEMENTALBASICSDICE",
	[99] = "SWKELEMENTALBASICSDICE", [100] = "SWKELEMENTALBASICSDICE", [101] = "SWKELEMENTALBASICSDICE", [102] = "SWKELEMENTALBASICSDICE", [103] = "SWKELEMENTALBASICSDICE",
	[106] = "SWKELEMENTALBASICSDICE", [107] = "SWKELEMENTALBASICSDICE", [108] = "SWKELEMENTALBASICSDICE", [109] = "SWKELEMENTALBASICSDICE",
	[110] = "SWKWIZARDWROUGHTDICE", [111] = "SWKWIZARDWROUGHTDICE", [112] = "SWKWIZARDWROUGHTDICE", [113] = "SWKWIZARDWROUGHTDICE", [114] = "SWKWIZARDWROUGHTDICE",
	[115] = "SWKWIZARDWROUGHTDICE", [116] = "SWKWIZARDWROUGHTDICE", [117] = "SWKWIZARDWROUGHTDICE", [118] = "SWKWIZARDWROUGHTDICE", [119] = "SWKWIZARDWROUGHTDICE",
	[120] = "SWKWIZARDWROUGHTDICE", [121] = "SWKWIZARDWROUGHTDICE", [122] = "SWKWIZARDWROUGHTDICE", [123] = "SWKWIZARDWROUGHTDICE", [124] = "SWKWIZARDWROUGHTDICE",
	[125] = "SWKWIZARDWROUGHTDICE",
	[130] = "SWKARTIFICERDICE", [131] = "SWKARTIFICERDICE", [132] = "SWKARTIFICERDICE", [133] = "SWKARTIFICERDICE", [134] = "SWKARTIFICERDICE",
	[135] = "SWKARTIFICERDICE", [136] = "SWKARTIFICERDICE", [137] = "SWKARTIFICERDICE", [138] = "SWKARTIFICERDICE", [139] = "SWKARTIFICERDICE",
	[140] = "SWKARTIFICERDICE", [141] = "SWKARTIFICERDICE",
	[150] = "SWKANNULUSOFFOCUSDICE", [151] = "SWKANNULUSOFFOCUSDICE", [152] = "SWKANNULUSOFFOCUSDICE", [153] = "SWKANNULUSOFFOCUSDICE", [154] = "SWKANNULUSOFFOCUSDICE",
	[155] = "SWKANNULUSOFFOCUSDICE", [156] = "SWKANNULUSOFFOCUSDICE", [157] = "SWKANNULUSOFFOCUSDICE", [158] = "SWKANNULUSOFFOCUSDICE", [159] = "SWKANNULUSOFFOCUSDICE",
	[160] = "SWKANNULUSOFFOCUSDICEFX", [161] = "SWKANNULUSOFFOCUSDICEFX", [162] = "SWKANNULUSOFFOCUSDICEFX", [163] = "SWKANNULUSOFFOCUSDICEFX", [164] = "SWKANNULUSOFFOCUSDICEFX",
	[165] = "SWKANNULUSOFFOCUSDICEFX", [166] = "SWKANNULUSOFFOCUSDICEFX", [167] = "SWKANNULUSOFFOCUSDICEFX", [168] = "SWKANNULUSOFFOCUSDICEFX", [169] = "SWKANNULUSOFFOCUSDICEFX",
	[170] = "SWKANNULUSOFFOCUSDICE", [171] = "SWKANNULUSOFFOCUSDICE", [172] = "SWKANNULUSOFFOCUSDICE", [173] = "SWKANNULUSOFFOCUSDICE", [174] = "SWKANNULUSOFFOCUSDICE",
	[175] = "SWKANNULUSOFFOCUSDICE", [177] = "SWKANNULUSOFFOCUSDICE", [178] = "SWKANNULUSOFFOCUSDICE", [179] = "SWKANNULUSOFFOCUSDICE",
	[180] = "SWKANNULUSOFFOCUSDICEFX", [181] = "SWKANNULUSOFFOCUSDICEFX", [182] = "SWKANNULUSOFFOCUSDICEFX", [183] = "SWKANNULUSOFFOCUSDICEFX", [184] = "SWKANNULUSOFFOCUSDICEFX",
	[185] = "SWKANNULUSOFFOCUSDICEFX", [187] = "SWKANNULUSOFFOCUSDICEFX", [188] = "SWKANNULUSOFFOCUSDICEFX", [189] = "SWKANNULUSOFFOCUSDICEFX",
	[190] = "SWKKNOTSOFFATEDICE", [191] = "SWKKNOTSOFFATEDICE", [192] = "SWKKNOTSOFFATEDICE", [193] = "SWKKNOTSOFFATEDICE", [194] = "SWKKNOTSOFFATEDICE",
	[195] = "SWKKNOTSOFFATEDICE", [196] = "SWKKNOTSOFFATEDICE", [197] = "SWKKNOTSOFFATEDICE", [198] = "SWKKNOTSOFFATEDICE", [199] = "SWKKNOTSOFFATEDICE",
	[200] = "SWKKNOTSOFFATEDICEFX", [201] = "SWKKNOTSOFFATEDICEFX", [202] = "SWKKNOTSOFFATEDICEFX", [203] = "SWKKNOTSOFFATEDICEFX", [204] = "SWKKNOTSOFFATEDICEFX",
	[205] = "SWKKNOTSOFFATEDICEFX", [206] = "SWKKNOTSOFFATEDICEFX", [207] = "SWKKNOTSOFFATEDICEFX", [208] = "SWKKNOTSOFFATEDICEFX", [209] = "SWKKNOTSOFFATEDICEFX",
	[210] = "SWKKNOTSOFFATEDICE", [211] = "SWKKNOTSOFFATEDICE", [212] = "SWKKNOTSOFFATEDICE", [213] = "SWKKNOTSOFFATEDICE", [214] = "SWKKNOTSOFFATEDICE",
	[215] = "SWKKNOTSOFFATEDICE", [216] = "SWKKNOTSOFFATEDICE", [217] = "SWKKNOTSOFFATEDICE", [218] = "SWKKNOTSOFFATEDICE", [219] = "SWKKNOTSOFFATEDICE",
	[220] = "SWKKNOTSOFFATEDICEFX", [221] = "SWKKNOTSOFFATEDICEFX", [222] = "SWKKNOTSOFFATEDICEFX", [223] = "SWKKNOTSOFFATEDICEFX", [224] = "SWKKNOTSOFFATEDICEFX",
	[225] = "SWKKNOTSOFFATEDICEFX", [226] = "SWKKNOTSOFFATEDICEFX", [227] = "SWKKNOTSOFFATEDICEFX", [228] = "SWKKNOTSOFFATEDICEFX", [229] = "SWKKNOTSOFFATEDICEFX",
	[230] = "SWKBLOODDICE", [231] = "SWKBLOODDICE", [232] = "SWKBLOODDICE", [233] = "SWKBLOODDICE", [234] = "SWKBLOODDICE",
	[235] = "SWKBLOODDICE", [236] = "SWKBLOODDICE", [237] = "SWKBLOODDICE", [238] = "SWKBLOODDICE", [239] = "SWKBLOODDICE",
	[240] = "SWKSTARSANDCLOVERS", [241] = "SWKSTARSANDCLOVERS", [242] = "SWKSTARSANDCLOVERS", [243] = "SWKSTARSANDCLOVERS", [244] = "SWKSTARSANDCLOVERS",
	[245] = "SWKSTARSANDCLOVERS", [246] = "SWKSTARSANDCLOVERS", [247] = "SWKSTARSANDCLOVERS", [248] = "SWKSTARSANDCLOVERS", [249] = "SWKSTARSANDCLOVERS",
	[250] = "SWKHEARTSANDSKULLS", [251] = "SWKHEARTSANDSKULLS", [252] = "SWKHEARTSANDSKULLS", [253] = "SWKHEARTSANDSKULLS", [254] = "SWKHEARTSANDSKULLS",
	[255] = "SWKHEARTSANDSKULLS", [256] = "SWKHEARTSANDSKULLS", [257] = "SWKHEARTSANDSKULLS", [258] = "SWKHEARTSANDSKULLS", [259] = "SWKHEARTSANDSKULLS",
	[260] = "SWKMONSTERSDICE1", [261] = "SWKMONSTERSDICE1", [262] = "SWKMONSTERSDICE1", [263] = "SWKMONSTERSDICE1", [264] = "SWKMONSTERSDICE1",
	[265] = "SWKMONSTERSDICE1", [266] = "SWKMONSTERSDICE1", [267] = "SWKMONSTERSDICE1", [268] = "SWKMONSTERSDICE1", [269] = "SWKMONSTERSDICE1",
	[270] = "SWKMONSTERSDICE1", [271] = "SWKMONSTERSDICE1", [272] = "SWKMONSTERSDICE1", [273] = "SWKMONSTERSDICE1", [274] = "SWKMONSTERSDICE1",
	[275] = "SWKMONSTERSDICE1", [276] = "SWKMONSTERSDICE1", [277] = "SWKMONSTERSDICE1", [278] = "SWKMONSTERSDICE1", [279] = "SWKMONSTERSDICE1",
	[280] = "SWKMONSTERSDICE1", [281] = "SWKMONSTERSDICE1",
	[282] = "SWKDRAGONSDICE1", [283] = "SWKDRAGONSDICE1", [284] = "SWKDRAGONSDICE1",
	[285] = "SWKDRAGONSDICE1", [286] = "SWKDRAGONSDICE1", [287] = "SWKDRAGONSDICE1", [288] = "SWKDRAGONSDICE1", [289] = "SWKDRAGONSDICE1",
	[290] = "SWKDRAGONSDICE1", [291] = "SWKDRAGONSDICE1", [292] = "SWKDRAGONSDICE1", [293] = "SWKDRAGONSDICE1", [294] = "SWKDRAGONSDICE1",
	[295] = "SWKDRAGONSDICE1", [296] = "SWKDRAGONSDICE1", [297] = "SWKDRAGONSDICE1", [298] = "SWKDRAGONSDICE1", [299] = "SWKDRAGONSDICE1",
	[300] = "SWKDRAGONSDICE1", [301] = "SWKDRAGONSDICE1",
	[302] = "SWKMONSTERSDICE2", [303] = "SWKMONSTERSDICE2", [304] = "SWKMONSTERSDICE2",
	[305] = "SWKMONSTERSDICE2", [306] = "SWKMONSTERSDICE2", [307] = "SWKMONSTERSDICE2", [308] = "SWKMONSTERSDICE2", [309] = "SWKMONSTERSDICE2",
	[310] = "SWKMONSTERSDICE2", [311] = "SWKMONSTERSDICE2", [312] = "SWKMONSTERSDICE2", [313] = "SWKMONSTERSDICE2", [314] = "SWKMONSTERSDICE2",
	[315] = "SWKMONSTERSDICE2", [316] = "SWKMONSTERSDICE2", [317] = "SWKMONSTERSDICE2", [318] = "SWKMONSTERSDICE2", [319] = "SWKMONSTERSDICE2",
	[320] = "SWKMONSTERSDICE2", [321] = "SWKMONSTERSDICE2",
	[322] = "SWKFANTASYDICE1", [323] = "SWKFANTASYDICE1", [324] = "SWKFANTASYDICE1",
	[325] = "SWKFANTASYDICE1", [326] = "SWKFANTASYDICE1", [327] = "SWKFANTASYDICE1", [328] = "SWKFANTASYDICE1", [329] = "SWKFANTASYDICE1",
	[330] = "SWKFANTASYDICE1", [331] = "SWKFANTASYDICE1", [332] = "SWKFANTASYDICE1", [333] = "SWKFANTASYDICE1", [334] = "SWKFANTASYDICE1",
	[335] = "SWKFANTASYDICE1", [336] = "SWKFANTASYDICE1", [337] = "SWKFANTASYDICE1", [338] = "SWKFANTASYDICE1", [339] = "SWKFANTASYDICE1",
	[340] = "SWKFANTASYDICE1", [341] = "SWKFANTASYDICE1", [342] = "SWKFANTASYDICE1", [343] = "SWKFANTASYDICE1", [344] = "SWKFANTASYDICE1",
	[345] = "SWKFANTASYDICE1",
	[346] = "SWKPROMODICE", [347] = "SWKPROMODICE", [348] = "SWKPROMODICE", [349] = "SWKPROMODICE",
	[350] = "SWKPROMODICE", [351] = "SWKPROMODICE",
	[352] = "SWKFANTASYDICE2", [353] = "SWKFANTASYDICE2", [354] = "SWKFANTASYDICE2",
	[355] = "SWKFANTASYDICE2", [356] = "SWKFANTASYDICE2", [357] = "SWKFANTASYDICE2", [358] = "SWKFANTASYDICE2", [359] = "SWKFANTASYDICE2",
	[360] = "SWKFANTASYDICE2", [361] = "SWKFANTASYDICE2", [362] = "SWKFANTASYDICE2", [363] = "SWKFANTASYDICE2", [364] = "SWKFANTASYDICE2",
	[365] = "SWKFANTASYDICE2", [366] = "SWKFANTASYDICE2", [367] = "SWKFANTASYDICE2", [368] = "SWKFANTASYDICE2", [369] = "SWKFANTASYDICE2",
	[370] = "SWKFANTASYDICE2", [371] = "SWKFANTASYDICE2",
};

local _tDiceSkinAttributeInfo = {
	[0] = {bTintable = true},
	[1] = {bDisabled = true},
	[5] = {bTintable = true},
	[6] = {bTintable = true},
	[9] = {bTintable = true},
	[10] = {bFX = true},
	[11] = {bFX = true},
	[12] = {bFX = true},
	[13] = {bFX = true},
	[14] = {bFX = true},
	[15] = {bFX = true},
	[16] = {bFX = true},
	[17] = {bFX = true},
	[18] = {bFX = true},
	[19] = {bFX = true},
	[20] = {bFX = true},
	[21] = {bFX = true},
	[22] = {bFX = true},
	[23] = {bFX = true},
	[24] = {bFX = true},
	[25] = {bFX = true},
	[26] = {bFX = true},
	[27] = {bFX = true},
	[28] = {bFX = true},
	[29] = {bFX = true},
	[30] = {bFX = true, bTrail = true},
	[31] = {bFX = true, bTrail = true},
	[32] = {bFX = true, bTrail = true},
	[33] = {bFX = true, bTrail = true},
	[34] = {bFX = true, bTrail = true},
	[35] = {bFX = true, bTrail = true},
	[36] = {bFX = true, bTrail = true},
	[37] = {bFX = true, bTrail = true},
	[38] = {bFX = true, bTrail = true},
	[39] = {bFX = true, bTrail = true},
	[40] = {bFX = true},
	[41] = {bFX = true},
	[42] = {bFX = true},
	[43] = {bFX = true},
	[44] = {bFX = true},
	[45] = {bFX = true},
	[46] = {bFX = true},
	[47] = {bFX = true},
	[48] = {bFX = true},
	[49] = {bFX = true},
	[50] = {bFX = true},
	[51] = {bFX = true},
	[52] = {bFX = true},
	[53] = {bFX = true},
	[54] = {bFX = true},
	[55] = {bFX = true},
	[56] = {bFX = true},
	[57] = {bFX = true},
	[58] = {bFX = true},
	[59] = {bFX = true},
	[60] = {bTrail = true},
	[61] = {bTrail = true},
	[62] = {bTrail = true},
	[63] = {bTrail = true},
	[64] = {bTrail = true},
	[65] = {bTrail = true},
	[66] = {bTrail = true},
	[67] = {bTrail = true},
	[68] = {bTrail = true},
	[69] = {bTrail = true},
	[70] = {bTrail = true},
	[71] = {bTrail = true},
	[72] = {bTrail = true},
	[73] = {bTrail = true},
	[74] = {bTrail = true},
	[75] = {bTrail = true},
	[76] = {bTrail = true},
	[77] = {bTrail = true},
	[78] = {bTrail = true},
	[79] = {bTrail = true},
	[80] = {bFX = true},
	[81] = {bFX = true},
	[82] = {bFX = true},
	[83] = {bFX = true},
	[84] = {bFX = true},
	[85] = {bFX = true},
	[86] = {bFX = true},
	[87] = {bFX = true},
	[88] = {bFX = true},
	[89] = {bFX = true},
	[90] = {bDisabled = true},
	[91] = {bFX = true, bTintable = true},
	[92] = {bTintable = true},
	[93] = {bTintable = true},
	[110] = {bTintable = true},
	[111] = {bTintable = true},
	[130] = {bTintable = true},
	[150] = {bTintable = true},
	[160] = {bTrail = true, bTintable = true},
	[161] = {bTrail = true},
	[162] = {bTrail = true},
	[163] = {bTrail = true},
	[164] = {bTrail = true},
	[165] = {bTrail = true},
	[166] = {bTrail = true},
	[167] = {bTrail = true},
	[168] = {bTrail = true},
	[169] = {bTrail = true},
	[175] = {bTintable = true},
	[177] = {bTintable = true},
	[178] = {bTintable = true},
	[179] = {bTintable = true},
	[180] = {bTrail = true},
	[181] = {bTrail = true},
	[182] = {bTrail = true},
	[183] = {bTrail = true},
	[184] = {bTrail = true},
	[185] = {bTrail = true, bTintable = true},
	[187] = {bTrail = true, bTintable = true},
	[188] = {bTrail = true, bTintable = true},
	[189] = {bTrail = true, bTintable = true},
	[190] = {bTintable = true},
	[194] = {bTintable = true},
	[200] = {bTrail = true, bTintable = true},
	[201] = {bTrail = true},
	[202] = {bTrail = true},
	[203] = {bTrail = true},
	[204] = {bTrail = true, bTintable = true},
	[205] = {bTrail = true},
	[206] = {bTrail = true},
	[207] = {bTrail = true},
	[208] = {bTrail = true},
	[209] = {bTrail = true},
	[219] = {bTintable = true},
	[220] = {bTrail = true},
	[221] = {bTrail = true},
	[222] = {bTrail = true},
	[223] = {bTrail = true},
	[224] = {bTrail = true},
	[225] = {bTrail = true},
	[226] = {bTrail = true},
	[227] = {bTrail = true},
	[228] = {bTrail = true},
	[229] = {bTrail = true, bTintable = true},
	[230] = {bTrail = true},
	[231] = {bTrail = true},
	[232] = {bTrail = true},
	[233] = {bTrail = true},
	[234] = {bTrail = true},
	[235] = {bTrail = true, bTintable = true},
	[236] = {bTrail = true, bTintable = true},
	[237] = {bTrail = true, bTintable = true},
	[238] = {bTrail = true, bTintable = true},
	[239] = {bTrail = true, bTintable = true},
	[241] = {bTrail = true},
	[242] = {bTrail = true},
	[243] = {bTrail = true},
	[246] = {bTrail = true},
	[247] = {bTrail = true},
	[248] = {bTrail = true},
	[251] = {bTrail = true},
	[252] = {bTrail = true},
	[253] = {bTrail = true},
	[254] = {bTrail = true},
	[255] = {bTrail = true},
	[256] = {bTrail = true},
	[257] = {bTrail = true},
	[258] = {bTrail = true},
	[259] = {bTrail = true},
	[271] = {bFX = true},
	[272] = {bFX = true},
	[273] = {bFX = true},
	[274] = {bFX = true},
	[275] = {bFX = true},
	[276] = {bFX = true},
	[277] = {bFX = true},
	[278] = {bFX = true},
	[279] = {bFX = true},
	[280] = {bFX = true, bTrail = true},
	[281] = {bFX = true},
	[292] = {bFX = true},
	[293] = {bFX = true},
	[294] = {bFX = true},
	[295] = {bTrail = true},
	[296] = {bFX = true},
	[297] = {bFX = true},
	[298] = {bFX = true},
	[299] = {bFX = true},
	[300] = {bTrail = true},
	[301] = {bFX = true},
	[312] = {bTrail = true},
	[313] = {bFX = true},
	[314] = {bTrail = true},
	[315] = {bTrail = true},
	[316] = {bTrail = true},
	[317] = {bFX = true},
	[318] = {bTrail = true},
	[319] = {bFX = true},
	[320] = {bTrail = true},
	[321] = {bTrail = true},
	[334] = {bFX = true, bTrail = true},
	[335] = {bTrail = true},
	[336] = {bTrail = true},
	[337] = {bFX = true, bTrail = true},
	[338] = {bFX = true, bTrail = true},
	[339] = {bFX = true, bTrail = true},
	[340] = {bFX = true},
	[341] = {bFX = true, bTrail = true},
	[342] = {bFX = true},
	[343] = {bFX = true},
	[344] = {bFX = true},
	[345] = {bFX = true},
	[347] = {bFX = true, bTrail = true},
	[349] = {bFX = true, bTrail = true},
	[351] = {bFX = true},
	[362] = {bFX = true},
	[363] = {bFX = true},
	[364] = {bFX = true},
	[365] = {bFX = true},
	[366] = {bFX = true},
	[367] = {bFX = true},
	[368] = {bFX = true},
	[369] = {bFX = true},
	[370] = {bFX = true},
	[371] = {bFX = true},
};

function getDiceSkinGroups()
	return _tDiceSkinGroups;
end
function getDiceSkinGroup(nID)
	return _tDiceSkinToGroupMap[nID] or DiceSkinData.DEFAULT_DICESKIN_GROUP;
end

function getDiceSkinGroupStoreID(sGroupID)
	return _tDiceSkinGroupStoreID[sGroupID];
end
function getDiceSkinIDStoreID(nID)
	local sGroup = DiceSkinData.getDiceSkinGroup(nID);
	local sGroupStoreID = DiceSkinData.getDiceSkinGroupStoreID(sGroup);
	if (sGroupStoreID or "") ~= "" then
		return sGroupStoreID;
	end
	return _tDiceSkinIDStoreID[nID];
end

function getDiceSkinAttributeInfo(nID)
	return _tDiceSkinAttributeInfo[nID];
end
